name: JumpBoots
version: '${project.version}'
main: com.ashkiano.jumpboots.JumpBoots
api-version: '1.16'
authors: [AshKiano]
commands:
  jumpboots:
    description: Gives the player a pair of jump boots.